import {colors} from "./colors";

const fontWeight = {
  light: "300",
  regular: "400",
  medium: "500",
  semibold: "600",
  bold: "700",
  black: "900",
};

export const fonts = {
  arizonia21_5: {
    fontFamily: "Arizonia",
    fontSize: "21px",
    letterSpacing: "0.05em",
    fontWeight: fontWeight.regular,
    color: colors.black,
  },
  arizonia24_5: {
    fontFamily: "Arizonia",
    fontSize: "24px",
    letterSpacing: "0.05em",
    fontWeight: fontWeight.regular,
    color: colors.black,
  },
  arizonia32_5: {
    fontFamily: "Arizonia",
    fontSize: "32px",
    letterSpacing: "0.05em",
    fontWeight: fontWeight.regular,
    color: colors.black,
  },
  arialBold12: {
    fontFamily: "Arial",
    fontSize: "12px",
    letterSpacing: "0em",
    fontWeight: fontWeight.bold,
    color: colors.black,
  },
  arialBold12_5: {
    fontFamily: "Arial",
    fontSize: "12px",
    letterSpacing: "0.05em",
    fontWeight: fontWeight.bold,
    color: colors.black,
  },
  arialBold14_5: {
    fontFamily: "Arial",
    fontSize: "14px",
    letterSpacing: "0.05em",
    fontWeight: fontWeight.bold,
    color: colors.black,
  },
  arialRegular16: {
    fontFamily: "Arial",
    fontSize: "16px",
    letterSpacing: "0em",
    fontWeight: fontWeight.regular,
    color: colors.black,
  },
  arialRegular17: {
    fontFamily: "Arial",
    fontSize: "17px",
    letterSpacing: "0em",
    fontWeight: fontWeight.regular,
    color: colors.black,
  },
  arialBold17: {
    fontFamily: "Arial",
    fontSize: "17px",
    letterSpacing: "0em",
    fontWeight: fontWeight.bold,
    color: colors.black,
  },
  arialRegular17_5: {
    fontFamily: "Arial",
    fontSize: "17px",
    letterSpacing: "0.05em",
    fontWeight: fontWeight.regular,
    color: colors.black,
  },
  arialBold17_5: {
    fontFamily: "Arial",
    fontSize: "17px",
    letterSpacing: "0.05em",
    fontWeight: fontWeight.bold,
    color: colors.black,
  },
  arialBold17_8: {
    fontFamily: "Arial",
    fontSize: "17px",
    letterSpacing: "0.08em",
    fontWeight: fontWeight.bold,
    color: colors.black,
  },
  arialBold22_5: {
    fontFamily: "Arial",
    fontSize: "22px",
    letterSpacing: "0.05em",
    fontWeight: fontWeight.bold,
    color: colors.black,
  },
  arialBold24_5: {
    fontFamily: "Arial",
    fontSize: "24px",
    letterSpacing: "0.05em",
    fontWeight: fontWeight.bold,
    color: colors.black,
  },
  arialBlack24_5: {
    fontFamily: "Arial",
    fontSize: "24px",
    letterSpacing: "0.05em",
    fontWeight: fontWeight.black,
    color: colors.black,
  },
  arialBold32_5: {
    fontFamily: "Arial",
    fontSize: "32px",
    letterSpacing: "0.05em",
    fontWeight: fontWeight.bold,
    color: colors.black,
  },
  arialBlack40_5: {
    fontFamily: "Arial",
    fontSize: "40px",
    letterSpacing: "0.05em",
    fontWeight: fontWeight.black,
    color: colors.black,
  },
  arialRegular50_5: {
    fontFamily: "Arial",
    fontSize: "50px",
    letterSpacing: "0.05em",
    fontWeight: fontWeight.regular,
    color: colors.black,
  },
};
